#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# add environment variable into files
dockerize -template /etc/php84/php.ini:/etc/php84/php.ini -template /etc/php84/php-fpm.conf:/etc/php84/php-fpm.conf -template /etc/php84/php-fpm.d:/etc/php84/php-fpm.d
